services:
  application:
    depends_on:
      mongodb:
        condition: service_started

    environment:
      spring.data.mongodb.host: "mongodb"

      spring.profiles.active: mongodb


  mongodb:
    mem_limit: 96m
    image: mongo:6.0.4
    container_name: ${_Values_root_name}-mongodb
    restart: 'no'
    ports:
      - 27017:27017
    volumes:
      - mongoconfig:/data/configdb
      - mongodata:/data/db
    networks:
      - ${_Values_root_name}-net
    environment:
      TZ: "Europe/Berlin"
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "mongodb"