services:
  application:
    depends_on:
      mongodb:
        condition: service_started

    environment:
      spring.profiles.active: mongodb

      #secrets
      spring.data.mongodb.port: "27017"
      spring.data.mongodb.host: "mongodb"
      spring.data.mongodb.username: "mongodb"
      spring.data.mongodb.password: "mongodb"
      authentication-database: "admin"
      database: "core"

  mongodb:
    mem_limit: 128m
    image: mongo:6.0.4
    container_name: ${_Values_root_name}-mongodb
    restart: 'no'
    ports:
      - 27017:27017
    volumes:
      - mongoconfig:/data/configdb
      - mongodata:/data/db
    networks:
      - ${_Values_root_name}-net
    environment:
      TZ: "Europe/Berlin"
      MONGO_INITDB_ROOT_USERNAME: "mongodb"
      MONGO_INITDB_ROOT_PASSWORD: "mongodb"