services:
  application:
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      spring.profiles.active: jpa

      spring.datasource.url: "jdbc:postgresql://postgres:5432/encore"
      spring.datasource.hikari.maximum-pool-size: "10"
      spring.datasource.hikari.connection-timeout: "10000"

      #secrets
      spring.datasource.username: "encore"
      spring.datasource.password: "encore"


  postgres:
    container_name: ${_Values_root_name}-postgres
    image: postgres:15.3
    restart: 'no'
    ports:
      - 50810:5432
    environment:
      TZ: "Europe/Berlin"
      POSTGRES_DB: "encore"

      #secrets
      POSTGRES_USER: "encore"
      POSTGRES_PASSWORD: "encore"

    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'

    healthcheck:
      test: "sh -c pg_isready"
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ${_Values_root_name}-net