#application
server:
  port: 50500

#monitoring
management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "health,prometheus,heapdump"

#openapi
springdoc.swagger-ui.path: /swagger-ui/index.html
springdoc.enable-native-support: "true"

#jaeger / zipkin
spring.application.name: encore
management.zipkin.tracing.endpoint: "http://localhost:9411/api/v2/spans"
management.tracing.sampling.probability: "1.0"
management.tracing.propagation.type: "B3"
management.tracing.enabled: "true"
logging.level.zipkin2.reporter: "ERROR"

#security
security.authentication.enabled: false
spring.security.user.name: "admin"
spring.security.user.password: "admin"

#s3
spring.cloud.aws.s3.enabled: "false"
spring.cloud.aws.s3.path-style-access-enabled: "true"
spring.cloud.aws.s3.endpoint: "http://localhost:9100"
spring.cloud.aws.credentials.access-key: "minioadmin"
spring.cloud.aws.credentials.secret-key: "minioadmin"
spring.cloud.aws.region.static: "eu"

#mongo
de.flapdoodle.mongodb.embedded.version: 6.0.4

#spring:
#  data:
#    mongodb:
#      port: 27017
#      host: localhost
#      authentication-database: admin
#      database: core
#      username: mongodb
#      password: mongodb

#jpa
spring.jpa.hibernate.ddl-auto: "create-drop"
spring.datasource.url: jdbc:h2:mem:person;DATABASE_TO_UPPER=FALSE
#spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres

#vaadin
spring.mustache.check-template-location: false
vaadin.whitelisted-packages: com.vaadin,org.vaadin,dev.hilla
vaadin.url-mapping: "/frontend/*"

#logging
logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

#profile
spring.profiles.active: "mongodb" #"mock"
database.provisioning.goals: "-import-demo-data -import-catalog-data"
